### ISSUE TITLE
MarkerColor Constant MisLabeled

### ISSUE THREAD

**Issue by waseymour** [dilgerma/newsbeat-room#1]
Hi Martin,

Line 101, the Const needs to be **MarkerColor**, it is currently **HighlightColor**, which causes a duplicate reference and prevents the script from running.

Awesome Script.

Walt

**Comment by dilgerma** [comment]
Hi Walt,

Marker and HighLight are 2 different things, not sure what exactly you point to.
Marker is the double click background highlighting on a certain message, highlighting is the highlighted message.

Can you post the error you get? I don´t have any errors?

**Comment by waseymour** [comment]
User Error, no issue.
